### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by jaimebayes** [nmccrea/sobot-rimulator#5]
Hi there, 

I try to run rimulator.py, but it ask for pygtk module, but I did not find it for anaconda python3, so i would like to ask you if you will migrate this project to python3 in the future.
Also, this project reminds me about an old project called pyrobotics for linux, are they related in some way?

Thanks in advance, JL

**Comment by nmccrea** [comment]
Hi @jaimebayes. Thanks for opening the issue.

This project is badly in need of maintenance. I am planning to come back and begin dedicating significant time to it again within the next few weeks. I am really looking forward to breathing some new life into this project, and the first order of business will be to port it to Python 3 and bring all the dependencies up to date. Hopefully that is only the beginning.

So stay tuned and there will be more updates soon.

**Comment by jaimebayes** [comment]
Hi, 

That sounds great, I am ready to give it a try, maybe as a jupyter o colab notebook.
I will stay tuned for the updates.

Best regards, JL

**Comment by tsadarsh** [comment]
@nmccrea I am a fairly new developer and I am comfortable with both Python2 and Python3. I see this as an opportunity to gain experience in software development. I will be glad to participate in porting this wonderful project to Python3. Maybe by assigning some chunks of code for new devs.

**Comment by nmccrea** [comment]
#3 has been merged and this project now supports Python 3 and Gtk 3. Many thanks to @paddy0489, sorry it took forever.

I will be updating the docs and making other improvements shortly. In the meantime, it looks the libraries you need to install in your conda environment are now Python 3, PyGObject, and Gtk3. It seems the Conda Forge is a good source:

```zsh
conda create --name sobot-rimulator python=3
conda activate sobot-rimulator
conda install -c conda-forge pygobject gtk3
python rimulator.py
```

Also @jaimebayes I never answered your question. No, this project is not related to Pyrobotics, it's actually based on [Sim.I.Am](http://jpdelacroix.com/software/simiam.html) by [JP de la Croix](http://jpdelacroix.com/). I think I need to make that credit more prominent, right now it's buried in `Manual.txt`.

@maddypie thanks so much for your offer to help with this. There was already a PR open and I was eager to just get it wrapped up ASAP since this was the most pressing issue for this project. I am putting together some thoughts for where I want to go with this project so there may be more opportunities to help.
